// Shape of the committed leaderboard snapshot and page (generated by scripts/build_leaderboard.py).
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const dir = path.join(__dirname, '..', 'leaderboard');
const data = JSON.parse(fs.readFileSync(path.join(dir, 'data.json'), 'utf8'));
const html = fs.readFileSync(path.join(dir, 'index.html'), 'utf8');

test('snapshot has timestamps and per-source freshness', () => {
  assert.match(data.generated_at, /^\d{4}-\d\d-\d\dT/);
  for (const s of ['bridgebench', 'openrouter']) assert.equal(typeof data.sources[s].stale, 'boolean');
  assert.match(data.sources.openrouter.fetched_at, /^\d{4}-/);
});

test('OpenRouter rows are collapsed and carry per-1M prices', () => {
  assert.ok(data.openrouter_models.length > 20);
  for (const m of data.openrouter_models) {
    assert.ok(!m.id.startsWith('~'), m.id);
    assert.ok(!m.id.endsWith(':batch'), m.id);
    for (const k of ['in', 'out']) assert.ok(m[k] === null || typeof m[k] === 'number');
  }
});

test('no API key is embedded anywhere', () => {
  for (const text of [html, JSON.stringify(data)]) assert.doesNotMatch(text, /sk-or-v1-[0-9a-f]{8}/);
});

test('page inlines the data and marks the leaderboard nav item current', () => {
  assert.ok(!html.includes('/*__LEADERBOARD_DATA__*/'));
  assert.match(html, /class="nav-leaderboard" href="\.\/" aria-current="page"/);
});

test('home nav links the leaderboard before the bug report button', () => {
  const home = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
  const lb = home.indexOf('class="nav-leaderboard" href="leaderboard/"');
  assert.ok(lb !== -1 && lb < home.indexOf('class="nav-bug"'));
});
