// Shape of the committed leaderboard snapshot and page (generated by scripts/build_leaderboard.py).
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const dir = path.join(__dirname, '..', 'benchmarks');
const data = JSON.parse(fs.readFileSync(path.join(dir, 'data.json'), 'utf8'));
const html = fs.readFileSync(path.join(dir, 'index.html'), 'utf8');

test('snapshot has timestamps and per-source freshness', () => {
  assert.match(data.generated_at, /^\d{4}-\d\d-\d\dT/);
  for (const s of ['bridgebench', 'openrouter']) assert.equal(typeof data.sources[s].stale, 'boolean');
  assert.match(data.sources.openrouter.fetched_at, /^\d{4}-/);
});

test('OpenRouter rows are collapsed and carry per-1M prices', () => {
  assert.ok(data.openrouter_models.length > 20);
  for (const m of data.openrouter_models) {
    assert.ok(!m.id.startsWith('~'), m.id);
    assert.ok(!m.id.endsWith(':batch'), m.id);
    for (const k of ['in', 'out']) assert.ok(m[k] === null || typeof m[k] === 'number');
  }
});

test('no API key is embedded anywhere', () => {
  for (const text of [html, JSON.stringify(data)]) assert.doesNotMatch(text, /sk-or-v1-[0-9a-f]{8}/);
});

test('page inlines the data and marks the leaderboard nav item current', () => {
  assert.ok(!html.includes('/*__LEADERBOARD_DATA__*/'));
  assert.match(html, /class="nav-leaderboard" href="\.\/" aria-current="page"/);
});

test('home nav puts Models on the left, outside the right-hand link group', () => {
  const home = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
  const models = home.indexOf('class="nav-leaderboard" href="benchmarks/"');
  const group = home.indexOf('<div class="site-nav-links">');
  assert.ok(models !== -1 && models < group, 'Models must come before the right-hand group');
  assert.match(home, /<span>Models<\/span>/);
  assert.match(home, /class="nav-install" href="#install">Install<\/a>/);
});

test('Models page groups the home link and Models on the left', () => {
  const start = html.indexOf('<div class="site-nav-start">');
  assert.ok(start !== -1 && start < html.indexOf('class="nav-leaderboard"'));
  assert.ok(html.indexOf('class="nav-leaderboard"') < html.indexOf('<div class="site-nav-links">'));
  assert.match(html, /class="nav-install" href="\.\.\/#install">Install<\/a>/);
});

test('model ids reveal on row hover/focus with a copy button, always shown on touch', () => {
  const tpl = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'leaderboard_template.html'), 'utf8');
  assert.match(tpl, /td\.model \.mid \{ position: absolute;[^}]*bottom: calc\(100% \+ 5px\)[^}]*opacity: 0;/);
  assert.match(tpl, /tbody tr:hover \.mid, tbody tr:focus-within \.mid \{[^}]*opacity: 1;/);
  assert.match(tpl, /@media \(hover: none\) \{\s*td\.model \.mid \{ position: static; opacity: 1;/);
  assert.match(tpl, /cb\.className = "id-copy"; cb\.dataset\.copyId = r\.id;/);
  assert.match(tpl, /copyText\(cp\.dataset\.copyId\)/);
});
